### ISSUE TITLE
As a user I want to be able to create an account so I can log in.

### ISSUE THREAD

**Issue by dirnberg18** [swenga-spuddy-project-team/spuddy#1]

**Comment by DrWulfric** [comment]
SignUp form added - alle für die Usererstellung notwendigen Datentypen sind implementiert, es fehlt noch die korrekte Implementierung der District Entity.

**Comment by DrWulfric** [comment]
District Entity wurde implementiert. Login Form funktioniert soweit. Allerdings fehlt Errorhandling für fehlerhafte Eingabe.
